spring:
  kafka:
    streams:
      application-id: sample-app-streams
    consumer:
      group-id: sample-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer

app:
  pipeline:
    source:
      topic: sample-topic
    sink:
      topic: ${app.pipeline.source.topic}-resequenced

resequence:
  state-store-name: resequence-buffer

logging:
  level:
    com.example.sampleapp: INFO
