spring:
  kafka:
    streams:
      application-id: sample-app-streams
    consumer:
      group-id: sample-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.sampleapp.domain.SampleRecord
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  pipeline:
    source:
      topic: sample-topic
    sink:
      topic: ${app.pipeline.source.topic}-resequenced

logging:
  level:
    com.example.sampleapp: INFO
